apiVersion: v1
kind: Service
metadata:
  name: streaming-tts-service
  namespace: default
  labels:
    app: streaming-tts-service
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: streaming-tts-service
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-tts-service-nodeport
  namespace: default
  labels:
    app: streaming-tts-service
spec:
  type: NodePort
  ports:
  - port: 3004
    targetPort: 3004
    nodePort: 30004
    protocol: TCP
    name: http
  selector:
    app: streaming-tts-service
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-tts-service-lb
  namespace: default
  labels:
    app: streaming-tts-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: streaming-tts-service